version: "3.9"

services:
  web:
    build: .

  elastic:
    image: "elasticsearch:latest"
    ports:
      - "8000:8000"

  redis:
      image: "redis:latest"

  postgresql:
    image: "postgres:latest"

