# Generated by Django 4.1.3 on 2022-11-12 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='0 GB', max_length=220)),
                ('parts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('second_title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('product_code', models.IntegerField(blank=True, default=utils.funcs.product_code, null=True, unique=True)),
                ('extra_code', models.CharField(blank=True, max_length=100, null=True)),
                ('iran_kala_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('password', models.CharField(blank=True, max_length=110, null=True)),
                ('mode', models.IntegerField(choices=[(1, 'physical'), (2, 'digital')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'publish'), (2, 'pending'), (3, 'dont_publish')], default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_distributor', to='shop.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'percent'), (2, 'price')], default=2)),
                ('name', models.CharField(max_length=120)),
                ('value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_size', to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('site_price', models.IntegerField(default=0)),
                ('major_price', models.IntegerField(default=0)),
                ('market_price', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('charity_type', models.IntegerField(choices=[(1, 'percent'), (2, 'price')], default=2)),
                ('charity', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_price', to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_mode', models.IntegerField(choices=[(1, 'base price'), (2, 'site option'), (3, 'off')], default=1)),
                ('send_price', models.IntegerField(default=0)),
                ('inventory', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_physical', to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=utils.funcs.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'mp4', 'png'], message='This Format Not Acceptable.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_images', to='distributor.distributor')),
            ],
        ),
        migrations.AddField(
            model_name='distributor',
            name='tags',
            field=models.ManyToManyField(related_name='distributor_tags', to='distributor.tag'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_distributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DigitalProductUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=900)),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_url', to='distributor.digital')),
            ],
        ),
        migrations.AddField(
            model_name='digital',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_digital', to='distributor.distributor'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=220)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_details', to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'percent'), (2, 'price')], default=2)),
                ('color', models.CharField(max_length=120)),
                ('value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_colors', to='distributor.distributor')),
            ],
        ),
    ]
