# Generated by Django 4.1.3 on 2022-11-12 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('mail', models.EmailField(blank=True, max_length=220, null=True, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=80, null=True)),
                ('website', models.URLField(blank=True, max_length=400, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(default='default/img.jpg', max_length=255, upload_to=user.models.User.user_dir)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(default='iran', max_length=150)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('national_code', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('introduction', models.CharField(blank=True, max_length=180, null=True)),
                ('role', models.IntegerField(choices=[(1, 'owner'), (2, 'total admin'), (3, 'usual admin'), (4, 'seller'), (5, 'service'), (6, 'distributor'), (7, 'writer'), (8, 'user')], default=8)),
                ('wallet', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
